// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// A span represents a single operation within a trace. Spans can be
/// nested to form a trace tree. Often, a trace contains a root span
/// that describes the end-to-end latency, and one or more subspans for
/// its sub-operations.
///
/// A trace can also contain multiple root spans, or none at all.
/// Spans do not need to be contiguous. There might be
/// gaps or overlaps between spans in a trace.
public struct Span: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the span in the following format:
  ///
  ///  * `projects/[PROJECT_ID]/traces/[TRACE_ID]/spans/[SPAN_ID]`
  ///
  /// `[TRACE_ID]` is a unique identifier for a trace within a project;
  /// it is a 32-character hexadecimal encoding of a 16-byte array. It should
  /// not be zero.
  ///
  /// `[SPAN_ID]` is a unique identifier for a span within a trace; it
  /// is a 16-character hexadecimal encoding of an 8-byte array. It should not
  /// be zero.
  /// .
  public var name: Swift.String = Swift.String()

  /// Required. The `[SPAN_ID]` portion of the span's resource name.
  public var spanId: Swift.String = Swift.String()

  /// The `[SPAN_ID]` of this span's parent span. If this is a root span,
  /// then this field must be empty.
  public var parentSpanId: Swift.String = Swift.String()

  /// Required. A description of the span's operation (up to 128 bytes).
  /// Cloud Trace displays the description in the
  /// Cloud console.
  /// For example, the display name can be a qualified method name or a file name
  /// and a line number where the operation is called. A best practice is to use
  /// the same display name within an application and at the same call point.
  /// This makes it easier to correlate spans in different traces.
  public var displayName: TruncatableString? = nil

  /// Required. The start time of the span. On the client side, this is the time
  /// kept by the local machine where the span execution starts. On the server
  /// side, this is the time when the server's application handler starts
  /// running.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Required. The end time of the span. On the client side, this is the time
  /// kept by the local machine where the span execution ends. On the server
  /// side, this is the time when the server application handler stops running.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// A set of attributes on the span. You can have up to 32 attributes per
  /// span.
  public var attributes: Span.Attributes? = nil

  /// Stack trace captured at the start of the span.
  public var stackTrace: StackTrace? = nil

  /// A set of time events. You can have up to 32 annotations and 128 message
  /// events per span.
  public var timeEvents: Span.TimeEvents? = nil

  /// Links associated with the span. You can have up to 128 links per Span.
  public var links: Span.Links? = nil

  /// Optional. The final status for this span.
  public var status: GoogleRpc.Status? = nil

  /// Optional. Set this parameter to indicate whether this span is in
  /// the same process as its parent. If you do not set this parameter,
  /// Trace is unable to take advantage of this helpful information.
  public var sameProcessAsParentSpan: GoogleCloudWkt.BoolValue? = nil

  /// Optional. The number of child spans that were generated while this span
  /// was active. If set, allows implementation to detect missing child spans.
  public var childSpanCount: GoogleCloudWkt.Int32Value? = nil

  /// Optional. Distinguishes between spans generated in a particular context.
  /// For example, two spans with the same name may be distinguished using
  /// `CLIENT` (caller) and `SERVER` (callee) to identify an RPC call.
  public var spanKind: Span.SpanKind = Span.SpanKind()

  /// Initialize a new instance of `Span`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Span().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A set of attributes as key-value pairs.
  public struct Attributes: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A set of attributes. Each attribute's key can be up to 128 bytes
    /// long. The value can be a string up to 256 bytes, a signed 64-bit integer,
    /// or the boolean values `true` or `false`. For example:
    ///
    ///     "/instance_id": { "string_value": { "value": "my-instance" } }
    ///     "/http/request_bytes": { "int_value": 300 }
    ///     "abc.com/myattribute": { "bool_value": false }
    public var attributeMap: [Swift.String: AttributeValue] = [:]

    /// The number of attributes that were discarded. Attributes can be discarded
    /// because their keys are too long or because there are too many attributes.
    /// If this value is 0 then all attributes are valid.
    public var droppedAttributesCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Attributes`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Attributes().with { $0.attributeMap = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.Span.Attributes"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A time-stamped annotation or message event in the Span.
  public struct TimeEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The timestamp indicating the time the event occurred.
    public var time: GoogleCloudWkt.Timestamp? = nil

    /// A `TimeEvent` can contain either an `Annotation` object or a
    /// `MessageEvent` object, but not both.
    public var value: OneOf_Value? = nil

    /// Initialize a new instance of `TimeEvent`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TimeEvent().with { $0.time = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case time = "time"
      case annotation = "annotation"
      case messageEvent = "messageEvent"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.time = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .time)

      var value: OneOf_Value? = nil
      let valueCheckAndSet = {
        if value != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'value'"))
        }
        value = $0
      }
      if let annotation = try container.decodeIfPresent(
        Span.TimeEvent.Annotation?.self, forKey: .annotation)
      {
        try valueCheckAndSet(.annotation(annotation))
      }
      if let messageEvent = try container.decodeIfPresent(
        Span.TimeEvent.MessageEvent?.self, forKey: .messageEvent)
      {
        try valueCheckAndSet(.messageEvent(messageEvent))
      }
      self.value = value
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.time, forKey: .time)

      if let choice = self.value {
        switch choice {
        case .annotation(let value):
          try container.encode(value, forKey: .annotation)
        case .messageEvent(let value):
          try container.encode(value, forKey: .messageEvent)
        }
      }
    }

    /// Text annotation with a set of attributes.
    public struct Annotation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// A user-supplied message describing the event. The maximum length for
      /// the description is 256 bytes.
      public var description: TruncatableString? = nil

      /// A set of attributes on the annotation. You can have up to 4 attributes
      /// per Annotation.
      public var attributes: Span.Attributes? = nil

      /// Initialize a new instance of `Annotation`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Annotation().with { $0.description = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.devtools.cloudtrace.v2.Span.TimeEvent.Annotation"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// An event describing a message sent/received between Spans.
    public struct MessageEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Type of MessageEvent. Indicates whether the message was sent or
      /// received.
      public var type: Span.TimeEvent.MessageEvent.Type_ = Span.TimeEvent.MessageEvent.Type_()

      /// An identifier for the MessageEvent's message that can be used to match
      /// `SENT` and `RECEIVED` MessageEvents.
      public var id: Swift.Int64 = Swift.Int64()

      /// The number of uncompressed bytes sent or received.
      public var uncompressedSizeBytes: Swift.Int64 = Swift.Int64()

      /// The number of compressed bytes sent or received. If missing, the
      /// compressed size is assumed to be the same size as the uncompressed
      /// size.
      public var compressedSizeBytes: Swift.Int64 = Swift.Int64()

      /// Initialize a new instance of `MessageEvent`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = MessageEvent().with { $0.type = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Indicates whether the message was sent or received.
      public enum Type_: Codable, Equatable, Sendable {
        /// Unknown event type.
        case unspecified
        /// Indicates a sent message.
        case sent
        /// Indicates a received message.
        case received
        /// Encodes an unknown integer value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownIntValue(Int)
        /// Encodes an unknown string value.
        ///
        /// The most common cause for an unknown values is for the service to send
        /// a value unknown to the library. We recommend you update your library to
        /// the latest version.
        case unknownStringValue(String)

        public init() {
          self = .unspecified
        }

        /// Returns the integer value associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown string value, this returns `nil`.
        public var intValue: Int? {
          switch self {
          case .unspecified: return 0
          case .sent: return 1
          case .received: return 2
          case .unknownIntValue(let v): return v
          case .unknownStringValue: return nil
          }
        }

        /// Returns the string value (or name) associated with the enumeration.
        ///
        /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
        public var stringValue: Swift.String? {
          switch self {
          case .unspecified: return "TYPE_UNSPECIFIED"
          case .sent: return "SENT"
          case .received: return "RECEIVED"
          case .unknownIntValue: return nil
          case .unknownStringValue(let v): return v
          }
        }

        /// Initialize from a string value.
        ///
        /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
        public init(stringValue: Swift.String) {
          switch stringValue {
          case "TYPE_UNSPECIFIED": self = .unspecified
          case "SENT": self = .sent
          case "RECEIVED": self = .received
          default: self = .unknownStringValue(stringValue)
          }
        }

        /// Initialize from an integer value.
        ///
        /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
        public init(intValue: Int) {
          switch intValue {
          case 0: self = .unspecified
          case 1: self = .sent
          case 2: self = .received
          default: self = .unknownIntValue(intValue)
          }
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.singleValueContainer()
          if let v = try? container.decode(Int.self) {
            self.init(intValue: v)
            return
          }
          if let s = try? container.decode(String.self) {
            if let v = Int(s) {
              self.init(intValue: v)
            } else {
              self.init(stringValue: s)
            }
            return
          }
          throw DecodingError.dataCorruptedError(
            in: container, debugDescription: "Expected enum value, must be integer or string.")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.singleValueContainer()
          switch self {
          case .unspecified: return try container.encode(0)
          case .sent: return try container.encode(1)
          case .received: return try container.encode(2)
          case .unknownIntValue(let v): return try container.encode(v)
          case .unknownStringValue(let v): return try container.encode(v)
          }
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.devtools.cloudtrace.v2.Span.TimeEvent.MessageEvent"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// A `TimeEvent` can contain either an `Annotation` object or a
    /// `MessageEvent` object, but not both.
    public enum OneOf_Value: Codable, Equatable, Sendable {
      /// Text annotation with a set of attributes.
      indirect case annotation(Span.TimeEvent.Annotation?)
      /// An event describing a message sent/received between Spans.
      indirect case messageEvent(Span.TimeEvent.MessageEvent?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.Span.TimeEvent"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A collection of `TimeEvent`s. A `TimeEvent` is a time-stamped annotation
  /// on the span, consisting of either user-supplied key:value pairs, or
  /// details of a message sent/received between Spans.
  public struct TimeEvents: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A collection of `TimeEvent`s.
    public var timeEvent: [Span.TimeEvent] = []

    /// The number of dropped annotations in all the included time events.
    /// If the value is 0, then no annotations were dropped.
    public var droppedAnnotationsCount: Swift.Int32 = Swift.Int32()

    /// The number of dropped message events in all the included time events.
    /// If the value is 0, then no message events were dropped.
    public var droppedMessageEventsCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `TimeEvents`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TimeEvents().with { $0.timeEvent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.Span.TimeEvents"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A pointer from the current span to another span in the same trace or in a
  /// different trace. For example, this can be used in batching operations,
  /// where a single batch handler processes multiple requests from different
  /// traces or when the handler receives a request from a different project.
  public struct Link: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The `[TRACE_ID]` for a trace within a project.
    public var traceId: Swift.String = Swift.String()

    /// The `[SPAN_ID]` for a span within a trace.
    public var spanId: Swift.String = Swift.String()

    /// The relationship of the current span relative to the linked span.
    public var type: Span.Link.Type_ = Span.Link.Type_()

    /// A set of attributes on the link. Up to 32 attributes can be
    /// specified per link.
    public var attributes: Span.Attributes? = nil

    /// Initialize a new instance of `Link`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Link().with { $0.traceId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The relationship of the current span relative to the linked span: child,
    /// parent, or unspecified.
    public enum Type_: Codable, Equatable, Sendable {
      /// The relationship of the two spans is unknown.
      case unspecified
      /// The linked span is a child of the current span.
      case childLinkedSpan
      /// The linked span is a parent of the current span.
      case parentLinkedSpan
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .childLinkedSpan: return 1
        case .parentLinkedSpan: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TYPE_UNSPECIFIED"
        case .childLinkedSpan: return "CHILD_LINKED_SPAN"
        case .parentLinkedSpan: return "PARENT_LINKED_SPAN"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .unspecified
        case "CHILD_LINKED_SPAN": self = .childLinkedSpan
        case "PARENT_LINKED_SPAN": self = .parentLinkedSpan
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .childLinkedSpan
        case 2: self = .parentLinkedSpan
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .childLinkedSpan: return try container.encode(1)
        case .parentLinkedSpan: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.Span.Link"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A collection of links, which are references from this span to a span
  /// in the same or different trace.
  public struct Links: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A collection of links.
    public var link: [Span.Link] = []

    /// The number of dropped links after the maximum size was enforced. If
    /// this value is 0, then no links were dropped.
    public var droppedLinksCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `Links`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Links().with { $0.link = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.Span.Links"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Type of span. Can be used to specify additional relationships between spans
  /// in addition to a parent/child relationship.
  public enum SpanKind: Codable, Equatable, Sendable {
    /// Unspecified. Do NOT use as default.
    /// Implementations MAY assume SpanKind.INTERNAL to be default.
    case unspecified
    /// Indicates that the span is used internally. Default value.
    case `internal`
    /// Indicates that the span covers server-side handling of an RPC or other
    /// remote network request.
    case server
    /// Indicates that the span covers the client-side wrapper around an RPC or
    /// other remote request.
    case client
    /// Indicates that the span describes producer sending a message to a broker.
    /// Unlike client and  server, there is no direct critical path latency
    /// relationship between producer and consumer spans (e.g. publishing a
    /// message to a pubsub service).
    case producer
    /// Indicates that the span describes consumer receiving a message from a
    /// broker. Unlike client and  server, there is no direct critical path
    /// latency relationship between producer and consumer spans (e.g. receiving
    /// a message from a pubsub service subscription).
    case consumer
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`internal`: return 1
      case .server: return 2
      case .client: return 3
      case .producer: return 4
      case .consumer: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SPAN_KIND_UNSPECIFIED"
      case .`internal`: return "INTERNAL"
      case .server: return "SERVER"
      case .client: return "CLIENT"
      case .producer: return "PRODUCER"
      case .consumer: return "CONSUMER"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SPAN_KIND_UNSPECIFIED": self = .unspecified
      case "INTERNAL": self = .`internal`
      case "SERVER": self = .server
      case "CLIENT": self = .client
      case "PRODUCER": self = .producer
      case "CONSUMER": self = .consumer
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`internal`
      case 2: self = .server
      case 3: self = .client
      case 4: self = .producer
      case 5: self = .consumer
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`internal`: return try container.encode(1)
      case .server: return try container.encode(2)
      case .client: return try container.encode(3)
      case .producer: return try container.encode(4)
      case .consumer: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudtrace.v2.Span"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
