// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// Service for collecting and viewing traces and spans within a trace.
///
/// A trace is a collection of spans corresponding to a single
/// operation or a set of operations in an application.
///
/// A span is an individual timed event which forms a node of the trace tree.
/// A single trace can contain spans from multiple services.
///
/// @Snippet(path: "TraceServiceQuickstart")
public class TraceServiceClient: Clients.TraceServiceProtocol {
  let inner: any Clients.TraceServiceStub

  /// Creates a new `TraceServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.TraceServiceStub = try Clients.TraceServiceTransport(options)
    inner = Clients.TraceServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TraceServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Batch writes new spans to new or existing traces. You cannot update
  /// existing spans.
  ///
  /// @Snippet(path: "TraceService_BatchWriteSpans")
  public func batchWriteSpans(
    request: BatchWriteSpansRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.batchWriteSpans(request: request, options: options)
  }

  /// Creates a new span.
  ///
  /// @Snippet(path: "TraceService_CreateSpan")
  public func createSpan(
    request: Span, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleDevtoolsCloudtraceV2.Span {
    try await self.inner.createSpan(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TraceServiceClient`.
  ///
  /// To mock `TraceServiceClient` change your functions to receive
  /// `some TraceServiceProtocol` or `any TraceServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TraceServiceProtocol {
    /// See `TraceServiceClient.batchWriteSpans`.
    func batchWriteSpans(request: BatchWriteSpansRequest) async throws

    /// See `TraceServiceClient.batchWriteSpans`.
    func batchWriteSpans(
      name: Swift.String,
      spans: [Span],
    ) async throws

    /// See `TraceServiceClient.createSpan`.
    func createSpan(request: Span) async throws -> GoogleDevtoolsCloudtraceV2.Span

    /// See `TraceServiceClient.batchWriteSpans`.
    func batchWriteSpans(
      request: BatchWriteSpansRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `TraceServiceClient.createSpan`.
    func createSpan(
      request: Span, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleDevtoolsCloudtraceV2.Span
  }
}

// Default implementations
extension Clients.TraceServiceProtocol {
  public func batchWriteSpans(request: BatchWriteSpansRequest) async throws {
    try await self.batchWriteSpans(request: request, options: .init())
  }

  public func batchWriteSpans(
    request: BatchWriteSpansRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func batchWriteSpans(
    name: Swift.String,
    spans: [Span],
  ) async throws {
    let request = BatchWriteSpansRequest().with {
      $0.name = name
      $0.spans = spans
    }
    try await self.batchWriteSpans(request: request)
  }

  public func createSpan(request: Span) async throws -> GoogleDevtoolsCloudtraceV2.Span {
    try await self.createSpan(request: request, options: .init())
  }

  public func createSpan(
    request: Span, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleDevtoolsCloudtraceV2.Span {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
