// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The allowed types for `[VALUE]` in a `[KEY]:[VALUE]` attribute.
public struct AttributeValue: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The type of the value.
  public var value: OneOf_Value? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AttributeValue`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AttributeValue().with { $0.stringValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let stringValue = CodingKeys(stringValue: "stringValue")
    static let intValue = CodingKeys(stringValue: "intValue")
    static let boolValue = CodingKeys(stringValue: "boolValue")

    static let _knownKeys: Set<Swift.String> = [
      "stringValue",
      "intValue",
      "boolValue",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var value: OneOf_Value? = nil
    let valueCheckAndSet = {
      if value != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'value'"))
      }
      value = $0
    }
    if let stringValue = try container.decodeIfPresent(
      TruncatableString?.self, forKey: .stringValue)
    {
      try valueCheckAndSet(.stringValue(stringValue))
    }
    if let intValue = try container.decodeIfPresent(Swift.Int64.self, forKey: .intValue) {
      try valueCheckAndSet(.intValue(intValue))
    }
    if let boolValue = try container.decodeIfPresent(Swift.Bool.self, forKey: .boolValue) {
      try valueCheckAndSet(.boolValue(boolValue))
    }
    self.value = value
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.value {
      switch choice {
      case .stringValue(let value):
        try container.encode(value, forKey: .stringValue)
      case .intValue(let value):
        try container.encode(value, forKey: .intValue)
      case .boolValue(let value):
        try container.encode(value, forKey: .boolValue)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The type of the value.
  public enum OneOf_Value: Codable, Equatable, Sendable {
    /// A string up to 256 bytes long.
    indirect case stringValue(TruncatableString?)
    /// A 64-bit signed integer.
    case intValue(Swift.Int64)
    /// A Boolean value represented by `true` or `false`.
    case boolValue(Swift.Bool)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudtrace.v2.AttributeValue"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
