// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A call stack appearing in a trace.
public struct StackTrace: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Stack frames in this stack trace. A maximum of 128 frames are allowed.
  public var stackFrames: StackTrace.StackFrames? = nil

  /// The hash ID is used to conserve network bandwidth for duplicate
  /// stack traces within a single trace.
  ///
  /// Often multiple spans will have identical stack traces.
  /// The first occurrence of a stack trace should contain both the
  /// `stackFrame` content and a value in `stackTraceHashId`.
  ///
  /// Subsequent spans within the same request can refer
  /// to that stack trace by only setting `stackTraceHashId`.
  public var stackTraceHashId: Swift.Int64 = Swift.Int64()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `StackTrace`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StackTrace().with { $0.stackFrames = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let stackFrames = CodingKeys(stringValue: "stackFrames")
    static let stackTraceHashId = CodingKeys(stringValue: "stackTraceHashId")

    static let _knownKeys: Set<Swift.String> = [
      "stackFrames",
      "stackTraceHashId",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.stackFrames = try container.decodeIfPresent(
      StackTrace.StackFrames.self, forKey: .stackFrames)
    if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .stackTraceHashId) {
      self.stackTraceHashId = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.stackFrames, forKey: .stackFrames)
    try container.encode(self.stackTraceHashId, forKey: .stackTraceHashId)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Represents a single stack frame in a stack trace.
  public struct StackFrame: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The fully-qualified name that uniquely identifies the function or
    /// method that is active in this frame (up to 1024 bytes).
    public var functionName: TruncatableString? = nil

    /// An un-mangled function name, if `function_name` is mangled.
    /// To get information about name mangling, run
    /// [this search](https://www.google.com/search?q=cxx+name+mangling).
    /// The name can be fully-qualified (up to 1024 bytes).
    public var originalFunctionName: TruncatableString? = nil

    /// The name of the source file where the function call appears (up to 256
    /// bytes).
    public var fileName: TruncatableString? = nil

    /// The line number in `file_name` where the function call appears.
    public var lineNumber: Swift.Int64 = Swift.Int64()

    /// The column number where the function call appears, if available.
    /// This is important in JavaScript because of its anonymous functions.
    public var columnNumber: Swift.Int64 = Swift.Int64()

    /// The binary module from where the code was loaded.
    public var loadModule: Module? = nil

    /// The version of the deployed source code (up to 128 bytes).
    public var sourceVersion: TruncatableString? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `StackFrame`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StackFrame().with { $0.functionName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let functionName = CodingKeys(stringValue: "functionName")
      static let originalFunctionName = CodingKeys(stringValue: "originalFunctionName")
      static let fileName = CodingKeys(stringValue: "fileName")
      static let lineNumber = CodingKeys(stringValue: "lineNumber")
      static let columnNumber = CodingKeys(stringValue: "columnNumber")
      static let loadModule = CodingKeys(stringValue: "loadModule")
      static let sourceVersion = CodingKeys(stringValue: "sourceVersion")

      static let _knownKeys: Set<Swift.String> = [
        "functionName",
        "originalFunctionName",
        "fileName",
        "lineNumber",
        "columnNumber",
        "loadModule",
        "sourceVersion",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.functionName = try container.decodeIfPresent(
        TruncatableString.self, forKey: .functionName)
      self.originalFunctionName = try container.decodeIfPresent(
        TruncatableString.self, forKey: .originalFunctionName)
      self.fileName = try container.decodeIfPresent(TruncatableString.self, forKey: .fileName)
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .lineNumber) {
        self.lineNumber = value
      }
      if let value = try container.decodeIfPresent(Swift.Int64.self, forKey: .columnNumber) {
        self.columnNumber = value
      }
      self.loadModule = try container.decodeIfPresent(Module.self, forKey: .loadModule)
      self.sourceVersion = try container.decodeIfPresent(
        TruncatableString.self, forKey: .sourceVersion)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.functionName, forKey: .functionName)
      try container.encodeIfPresent(self.originalFunctionName, forKey: .originalFunctionName)
      try container.encodeIfPresent(self.fileName, forKey: .fileName)
      try container.encode(self.lineNumber, forKey: .lineNumber)
      try container.encode(self.columnNumber, forKey: .columnNumber)
      try container.encodeIfPresent(self.loadModule, forKey: .loadModule)
      try container.encodeIfPresent(self.sourceVersion, forKey: .sourceVersion)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.StackTrace.StackFrame"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A collection of stack frames, which can be truncated.
  public struct StackFrames: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Stack frames in this call stack.
    public var frame: [StackTrace.StackFrame] = []

    /// The number of stack frames that were dropped because there
    /// were too many stack frames.
    /// If this value is 0, then no stack frames were dropped.
    public var droppedFramesCount: Swift.Int32 = Swift.Int32()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `StackFrames`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StackFrames().with { $0.frame = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let frame = CodingKeys(stringValue: "frame")
      static let droppedFramesCount = CodingKeys(stringValue: "droppedFramesCount")

      static let _knownKeys: Set<Swift.String> = [
        "frame",
        "droppedFramesCount",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([StackTrace.StackFrame].self, forKey: .frame) {
        self.frame = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .droppedFramesCount) {
        self.droppedFramesCount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.frame, forKey: .frame)
      try container.encode(self.droppedFramesCount, forKey: .droppedFramesCount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.StackTrace.StackFrames"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudtrace.v2.StackTrace"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
