// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A call stack appearing in a trace.
public struct StackTrace: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Stack frames in this stack trace. A maximum of 128 frames are allowed.
  public var stackFrames: StackTrace.StackFrames? = nil

  /// The hash ID is used to conserve network bandwidth for duplicate
  /// stack traces within a single trace.
  ///
  /// Often multiple spans will have identical stack traces.
  /// The first occurrence of a stack trace should contain both the
  /// `stackFrame` content and a value in `stackTraceHashId`.
  ///
  /// Subsequent spans within the same request can refer
  /// to that stack trace by only setting `stackTraceHashId`.
  public var stackTraceHashId: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `StackTrace`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StackTrace().with { $0.stackFrames = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Represents a single stack frame in a stack trace.
  public struct StackFrame: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The fully-qualified name that uniquely identifies the function or
    /// method that is active in this frame (up to 1024 bytes).
    public var functionName: TruncatableString? = nil

    /// An un-mangled function name, if `function_name` is mangled.
    /// To get information about name mangling, run
    /// [this search](https://www.google.com/search?q=cxx+name+mangling).
    /// The name can be fully-qualified (up to 1024 bytes).
    public var originalFunctionName: TruncatableString? = nil

    /// The name of the source file where the function call appears (up to 256
    /// bytes).
    public var fileName: TruncatableString? = nil

    /// The line number in `file_name` where the function call appears.
    public var lineNumber: Swift.Int64 = Swift.Int64()

    /// The column number where the function call appears, if available.
    /// This is important in JavaScript because of its anonymous functions.
    public var columnNumber: Swift.Int64 = Swift.Int64()

    /// The binary module from where the code was loaded.
    public var loadModule: Module? = nil

    /// The version of the deployed source code (up to 128 bytes).
    public var sourceVersion: TruncatableString? = nil

    /// Initialize a new instance of `StackFrame`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StackFrame().with { $0.functionName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.StackTrace.StackFrame"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A collection of stack frames, which can be truncated.
  public struct StackFrames: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Stack frames in this call stack.
    public var frame: [StackTrace.StackFrame] = []

    /// The number of stack frames that were dropped because there
    /// were too many stack frames.
    /// If this value is 0, then no stack frames were dropped.
    public var droppedFramesCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `StackFrames`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StackFrames().with { $0.frame = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.devtools.cloudtrace.v2.StackTrace.StackFrames"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudtrace.v2.StackTrace"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
