// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Represents a string that might be shortened to a specified length.
public struct TruncatableString: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The shortened string. For example, if the original string is 500
  /// bytes long and the limit of the string is 128 bytes, then
  /// `value` contains the first 128 bytes of the 500-byte string.
  ///
  /// Truncation always happens on a UTF8 character boundary. If there
  /// are multi-byte characters in the string, then the length of the
  /// shortened string might be less than the size limit.
  public var value: Swift.String = Swift.String()

  /// The number of bytes removed from the original string. If this
  /// value is 0, then the string was not shortened.
  public var truncatedByteCount: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `TruncatableString`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TruncatableString().with { $0.value = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudtrace.v2.TruncatableString"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
